# Site settings
title: mxm
email: marsmxm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Currently interesting in: programming languages, learning machines...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.mxm.blue" # the base hostname & protocol for your site
github_username:  marsmxm

# Build settings
markdown: kramdown
